#!/bin/bash
set -e

# TODO!!!!!!!!
cp tmp_genesis.json home/config/genesis.json

# TODO!!!!!!!!!
ADMIN_ADDRESS="neutron1r49r67ufp37xnqqtpvetrnd4akm2xfkmg0uqmw"

BINARY=${BINARY:-neutrond}
CHAINID=${CHAINID:-test-1}
STAKEDENOM=${STAKEDENOM:-untrn}
TGE_CONTRACTS_BINARIES_DIR=${TGE_CONTRACTS_BINARIES_DIR:-../neutron-tge-contracts/artifacts}
DAO_CONTRACTS_BINARIES_DIR=${DAO_CONTRACTS_BINARIES_DIR:-../neutron-dao/artifacts}
ASTROPORT_CONTRACTS_BINARIES_DIR=${ASTROPORT_CONTRACTS_BINARIES_DIR:-../artifacts} # TODO
GENESIS_PATH=${GENESIS_PATH:-./genesis.json}

INSTANCE_ID_COUNTER=1


LOCKDROP_BINARY=$TGE_CONTRACTS_BINARIES_DIR/neutron_lockdrop-aarch64.wasm
AUCTION_BINARY=$TGE_CONTRACTS_BINARIES_DIR/neutron_auction-aarch64.wasm
CREDITS_BINARY=$TGE_CONTRACTS_BINARIES_DIR/credits-aarch64.wasm
AIRDROP_BINARY=$TGE_CONTRACTS_BINARIES_DIR/cw20_merkle_airdrop-aarch64.wasm
PRICE_FEED_BINARY=$TGE_CONTRACTS_BINARIES_DIR/neutron_price_feed-aarch64.wasm
TWAP_ORACLE_BINARY=$TGE_CONTRACTS_BINARIES_DIR/astroport_oracle-aarch64.wasm
LP_VESTING_BINARY=$TGE_CONTRACTS_BINARIES_DIR/neutron_lockdrop-aarch64.wasm # TODO

CREDITS_VAULT_BINARY=$DAO_CONTRACTS_BINARIES_DIR/credits_vault-aarch64.wasm
LOCKDROP_VAULT_BINARY=$DAO_CONTRACTS_BINARIES_DIR/lockdrop_vault-aarch64.wasm

ASTROPORT_SATELLITE_BINARY=$TGE_CONTRACTS_BINARIES_DIR/astroport_factory-aarch64.wasm # TODO
ASTROPORT_GENERATOR_BINARY=$TGE_CONTRACTS_BINARIES_DIR/astroport_factory-aarch64.wasm # TODO
ASTROPORT_FACTORY_BINARY=$TGE_CONTRACTS_BINARIES_DIR/astroport_factory-aarch64.wasm
ASTROPORT_PAIR_BINARY=$TGE_CONTRACTS_BINARIES_DIR/astroport_pair-aarch64.wasm
ASTROPORT_TOKEN_BINARY=$TGE_CONTRACTS_BINARIES_DIR/astroport_token-aarch64.wasm

function store_binary() {
  CONTRACT_BINARY_PATH=$1
  $BINARY add-wasm-message store "$CONTRACT_BINARY_PATH" --output json --run-as ${ADMIN_ADDRESS} --home ./home
  BINARY_ID=$(jq -r "[.app_state.wasm.gen_msgs[] | select(.store_code != null)] | length" "./home/config/genesis.json")
  echo "$BINARY_ID"
}

function generate_contract_address() {
  CODE_ID=$1
  CONTRACT_ADDRESS=$($BINARY debug generate-contract-address $INSTANCE_ID_COUNTER $CODE_ID)
  echo $CONTRACT_ADDRESS
}

echo "Initializing dao contract in genesis..."

# Uploading contracts
LOCKDROP_CONTRACT_BINARY_ID=$(store_binary "$LOCKDROP_BINARY")
AUCTION_CONTRACT_BINARY_ID=$(store_binary "$AUCTION_BINARY")
CREDITS_CONTRACT_BINARY_ID=$(store_binary "$CREDITS_BINARY")
AIDROP_CONTRACT_BINARY_ID=$(store_binary "$AIRDROP_BINARY")
PRICE_FEED_CONTRACT_BINARY_ID=$(store_binary "$PRICE_FEED_BINARY")
TWAP_ORACLE_CONTRACT_BINARY_ID=$(store_binary "$TWAP_ORACLE_BINARY")
LP_VESTING_CONTRACT_BINARY_ID=$(store_binary "$LP_VESTING_BINARY")
CREDITS_VAULT_CONTRACT_BINARY_ID=$(store_binary "$CREDITS_VAULT_BINARY")
LOCKDROP_VAULT_CONTRACT_BINARY_ID=$(store_binary "$LOCKDROP_VAULT_BINARY")
ASTROPORT_SATELLITE_CONTRACT_BINARY_ID=$(store_binary "$ASTROPORT_SATELLITE_BINARY")
ASTROPORT_GENERATOR_CONTRACT_BINARY_ID=$(store_binary "$ASTROPORT_GENERATOR_BINARY")
ASTROPORT_FACTORY_CONTRACT_BINARY_ID=$(store_binary "$ASTROPORT_FACTORY_BINARY")
ASTROPORT_PAIR_CONTRACT_BINARY_ID=$(store_binary "$ASTROPORT_PAIR_BINARY")
ASTROPORT_TOKEN_CONTRACT_BINARY_ID=$(store_binary "$ASTROPORT_TOKEN_BINARY")

# Contracts addresses pregeneration
LOCKDROP_CONTRACT_ADDRESS=$(generate_contract_address $LOCKDROP_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
AUCTION_CONTRACT_ADDRESS=$(generate_contract_address $AUCTION_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
CREDITS_CONTRACT_ADDRESS=$(generate_contract_address $CREDITS_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
AIDROP_CONTRACT_ADDRESS=$(generate_contract_address $AIDROP_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
PRICE_FEED_CONTRACT_ADDRESS=$(generate_contract_address $PRICE_FEED_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
USDC_TWAP_CONTRACT_ADDRESS=$(generate_contract_address $TWAP_ORACLE_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ATOM_TWAP_CONTRACT_ADDRESS=$(generate_contract_address $TWAP_ORACLE_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
USDC_LP_VESTING_CONTRACT_ADDRESS=$(generate_contract_address $LP_VESTING_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ATOM_LP_VESTING_CONTRACT_ADDRESS=$(generate_contract_address $LP_VESTING_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
CREDITS_VAULT_CONTRACT_ADDRESS=$(generate_contract_address $CREDITS_VAULT_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
LOCKDROP_VAULT_CONTRACT_ADDRESS=$(generate_contract_address $LOCKDROP_VAULT_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
# SEQUENCE IS IMPORTANT HERE
ASTROPORT_SATELLITE_CONTRACT_ADDRESS=$(generate_contract_address $ASTROPORT_SATELLITE_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ASTROPORT_GENERATOR_CONTRACT_ADDRESS=$(generate_contract_address $ASTROPORT_GENERATOR_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ASTROPORT_FACTORY_CONTRACT_ADDRESS=$(generate_contract_address $ASTROPORT_FACTORY_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ASTROPORT_USDC_PAIR_CONTRACT_ADDRESS=$(generate_contract_address $ASTROPORT_PAIR_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ASTROPORT_USDC_LP_TOKEN_CONTRACT_ADDRESS=$(generate_contract_address $ASTROPORT_TOKEN_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ASTROPORT_ATOM_PAIR_CONTRACT_ADDRESS=$(generate_contract_address $ASTROPORT_PAIR_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))
ASTROPORT_ATOM_LP_TOKEN_CONTRACT_ADDRESS=$(generate_contract_address $ASTROPORT_TOKEN_CONTRACT_BINARY_ID) && ((INSTANCE_ID_COUNTER++))


echo "LOCKDROP_CONTRACT_ADDRESS:" $LOCKDROP_CONTRACT_ADDRESS
echo "AUCTION_CONTRACT_ADDRESS:" $AUCTION_CONTRACT_ADDRESS
echo "CREDITS_CONTRACT_ADDRESS:" $CREDITS_CONTRACT_ADDRESS
echo "AIDROP_CONTRACT_ADDRESS:" $AIDROP_CONTRACT_ADDRESS
echo "PRICE_FEED_CONTRACT_ADDRESS:" $PRICE_FEED_CONTRACT_ADDRESS
echo "USDC_TWAP_CONTRACT_ADDRESS:" $USDC_TWAP_CONTRACT_ADDRESS
echo "ATOM_TWAP_CONTRACT_ADDRESS:" $ATOM_TWAP_CONTRACT_ADDRESS
echo "USDC_LP_VESTING_CONTRACT_ADDRESS:" $USDC_LP_VESTING_CONTRACT_ADDRESS
echo "ATOM_LP_VESTING_CONTRACT_ADDRESS:" $ATOM_LP_VESTING_CONTRACT_ADDRESS
echo "CREDITS_VAULT_CONTRACT_ADDRESS:" $CREDITS_VAULT_CONTRACT_ADDRESS
echo "LOCKDROP_VAULT_CONTRACT_ADDRESS:" $LOCKDROP_VAULT_CONTRACT_ADDRESS
echo "ASTROPORT_SATELLITE_CONTRACT_ADDRESS:" $ASTROPORT_SATELLITE_CONTRACT_ADDRESS
echo "ASTROPORT_GENERATOR_CONTRACT_ADDRESS:" $ASTROPORT_GENERATOR_CONTRACT_ADDRESS
echo "ASTROPORT_FACTORY_CONTRACT_ADDRESS:" $ASTROPORT_FACTORY_CONTRACT_ADDRESS
echo "ASTROPORT_USDC_PAIR_CONTRACT_ADDRESS:" $ASTROPORT_USDC_PAIR_CONTRACT_ADDRESS
echo "ASTROPORT_ATOM_PAIR_CONTRACT_ADDRESS:" $ASTROPORT_ATOM_PAIR_CONTRACT_ADDRESS
echo "ASTROPORT_USDC_LP_TOKEN_CONTRACT_ADDRESS:" $ASTROPORT_USDC_LP_TOKEN_CONTRACT_ADDRESS
echo "ASTROPORT_ATOM_LP_TOKEN_CONTRACT_ADDRESS:" $ASTROPORT_ATOM_LP_TOKEN_CONTRACT_ADDRESS